SHOW GLOBAL VARIABLES;

SHOW GLOBAL VARIABLES LIKE '%char%';

SELECT @@GLOBAL.autocommit;

SHOW SESSION VARIABLES;

SET @name = 'John';

SET @COUNT = 100;
SELECT COUNT(*) FROM employees INTO @COUNT;
SELECT @COUNT;

SET @num1 = 1;
SET @num2 = 2;
SET @SUM = @num1 + @num2;
SELECT @SUM;

BEGIN 	
	DECLARE num1 INT DEFAULT 1;
	DECLARE num2 INT DEFAULT 2;
	DECLARE SUM INT;
	SET SUM = num1 + num2;
	SELECT SUM;
END
